name: Labels
on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - opened
      - synchronize
      - reopened

permissions: {}

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
    - run: echo "Done adding labels"
